---

# Commonly adjusted application variables -
# everything we expect the user to consider changing.
# To avoid clutter, put less-common variables in 'vars/main.yaml'

# Set to 'absent' to undeploy
{{cookiecutter.var_prefix}}_state: present

# The namespace to create for application deployment.
{{cookiecutter.var_prefix}}_namespace: {{cookiecutter.namespace}}

{% if cookiecutter.add_pvc|lower in ['y'] %}
# Persistent volume configuration
# The storageclass is 'blank', which implies the default class.
{{cookiecutter.var_prefix}}_volume_storageclass: longhorn
{{cookiecutter.var_prefix}}_volume_size_g: 1
{% endif %}

# Details of the application container image
{{cookiecutter.var_prefix}}_image_name: {{cookiecutter.image_name}}
{{cookiecutter.var_prefix}}_image_tag: '{{cookiecutter.image_tag}}'

{% if cookiecutter.add_ingress|lower in ['y'] %}
# The ingress hostname (http/https assumed)
{{cookiecutter.var_prefix}}_hostname: '{{cookiecutter.ingress_hostname}}'
# The ingress "let's Encrypt" certificate issuer.
# One of 'production' or 'staging'
{{cookiecutter.var_prefix}}_cert_issuer: production
{% endif %}

{% if cookiecutter.kind == 'cronjob' %}
# The CronJob Schedule
# Here we run at 04:07 every day.
{{cookiecutter.var_prefix}}_schedule: '7 4 * * *'
{% endif %}

{% if cookiecutter.add_secret|lower in ['y'] %}
# The pull-secret
{{cookiecutter.var_prefix}}_pull_secret: '00000000'
{% endif %}
