---

- name: Run prep
  ansible.builtin.include_tasks: prep.yaml

- name: Check KUBECONFIG
  ansible.builtin.assert:
    that:
    - {{cookiecutter.var_prefix}}_kubeconfig | string | length != 0

- name: Deploy
  module_defaults:
    group/k8s:
      kubeconfig: "{{ "{{" }} {{cookiecutter.var_prefix}}_kubeconfig {{ "}}" }}"
  block:

  - name: Run deploy play
    ansible.builtin.include_tasks: deploy.yaml
    when: {{cookiecutter.var_prefix}}_state | string == 'present'
  - name: Run undeploy play
    ansible.builtin.include_tasks: undeploy.yaml
    when: {{cookiecutter.var_prefix}}_state | string == 'absent'
