---

# Common playbook preparation.

# Expose ansible version
- name: Display Ansible version
  ansible.builtin.debug:
    var: ansible_version.full

# Expose all the installed Python modules...

- name: Capture pip freeze
  ansible.builtin.command: pip freeze
  register: freeze
  changed_when: false

- name: Display pip freeze
  ansible.builtin.debug:
    var: freeze.stdout_lines
