---

# Common playbook preparation.

# Expose ansible version
- name: Display Ansible version
  ansible.builtin.debug:
    var: ansible_version.full

# Expose all the installed Python modules...

- name: Capture pip freeze
  ansible.builtin.command: pip freeze
  register: freeze
  changed_when: false

- name: Display pip freeze
  ansible.builtin.debug:
    var: freeze.stdout_lines

# Kubernetes credentials ------------------------------------------------------

# We don't use the Kubernetes credentials directly,
# but we load them into variables here from their
# expected environment variables so that we can assert they've been set.
#
# The user can provide a HOST and KEY or a KUBECONFIG.

- name: Set initial authentication facts
  set_fact:
    k8s_auth_host: "{{ lookup('env', 'K8S_AUTH_HOST') }}"
    k8s_auth_api_key: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"
    k8s_config: "{{ lookup('env', 'KUBECONFIG') }}"
