---

# Common playbook preparation.

# Expose ansible version
- debug:
    var: ansible_version.full

# Expose all the installed Python modules...

- name: Capture pip freeze
  command: pip freeze
  register: freeze
  changed_when: false

- name: Display pip freeze
  debug:
    var: freeze.stdout_lines
