---

# Un-deploy (uninstall).
#
# To un-deploy, with no objects created outside the namespace,
# the fastest way is to delete the namespace.

- name: Delete namespace
  kubernetes.core.k8s:
    state: absent
    definition: "{{ "{{" }} lookup('template', 'namespace.yaml.j2') {{ "}}" }}"
    wait: yes
